---
title: "Modeling"
author: "David John Baker"
date: "12/23/2018"
output: html_document
---

## Plots and Modeling

Using our DATA from before, let's now try to make a plot where we predict X from Y.
First let's make this with ggplot2.

## Basic Linear Models 

Linear models are done with the ```lm()``` function and follow the general pattern of

> model <- lm(DV ~ IV, data = yourData)
> summary(model)

Models are saved as lists meaning you can access any part of the model with the ```$``` command on the object name.
Let's try to run some models on our DATA.

First, together let's run a model where we try to predict DV from IV.
Once saving this to an object, we can get the output from ```summary()```.

## Model Interpretation

PICTURE HERE OF THAT.

## Future

In the future, check out Hadely Wickham's [R For Data Science](https://r4ds.had.co.nz/) which will give you a solid introduction to R and all it can do.
Much of your time will also be spent on Stack Overflow,.
I also very much suggest setting up a Facebook group or something of people here that are about on the same skill level so that you can help each other out.
